#pragma config(Sensor, S2,     ultrasonic,     sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     gyro,           sensorEV3_Gyro)
#pragma config(Sensor, S4,     color,          sensorEV3_Color)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorD,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int white;
	int black;

	//Calibration part 1, place the robot on white and press up button.
	//This sets the white value
	//Press ok to break the loop
  while(getButtonPress(buttonEnter) != 1)
  {
    displayBigTextLine(3, "Place on White");
    displayBigTextLine(6, "Then Press Up");

    if(getButtonPress(buttonUp) == 1)
    {
      white = getColorReflected(color);
      displayBigTextLine(9, "Press OK");?
      sleep(500);
    }
  }

  sleep(2000);

	//Calibration part 2, place the robot on the line and press the down button.
	//This sets the white value.
  while(getButtonPress(buttonEnter) != 1)
  {
    displayBigTextLine(3, "Place on Line");
    displayBigTextLine(6, "Then Press Down");

    if(getButtonPress(buttonDown) == 1)
    {
      black = getColorReflected(color);
      displayBigTextLine(9, "Press OK");
			sleep(500);
    }
  }

  int threshold = (white + black) / 2; // Calculates the threshold value for the Line

	// Line following program
  while(true)
  {
    if(getColorReflected(color) < threshold)
    {
      setMotorSpeed(leftMotor, 50);
      setMotorSpeed(rightMotor, 30);
    }

    else
    {
      setMotorSpeed(leftMotor, 30);
      setMotorSpeed(rightMotor, 50);
    }
  }

}
