#pragma config(Sensor, S3,     ultrasonic,     sensorEV3_Ultrasonic)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


void goforward (int x)
{
	setMotorSpeed(leftMotor, x);
	setMotorSpeed(rightMotor, x);
}

task main()
{
	while(true)
	{
		while (getUSDistance(ultrasonic) > 50)
		{
			goforward(100);
			break;
		}

		while (getUSDistance(ultrasonic) > 25)
		{
			while (getUSDistance(ultrasonic) <50)
			{
				goforward(50);
				break;
			}
			break;
		}

		while (getUSDistance(ultrasonic) > 7)
		{
			while (getUSDistance(ultrasonic) < 25)
			{
				goforward(20);
				break;
			}
			break;
		}

		while (getUSDistance(ultrasonic) < 6)
		{
			goforward(-10);
			break;
		}

		while (getUSDistance(ultrasonic) > 6)
		{
			while (getUSDistance(ultrasonic) < 8)
			{
				goforward(0);
				break;
			}
			break;
		}
	}



}
