#pragma config(Sensor, S2,     ultrasonic,     sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     gyro,           sensorEV3_Gyro)
#pragma config(Sensor, S4,     colour,         sensorEV3_Color)
#pragma config(Motor,  motorA,          mediumMotor,   tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorD,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//




task main()
{
  int distance = 0;
  int setDistance;

  while(true)
  {
    displayBigTextLine(3, "Input Distance");
    displayBigTextLine(6, "Distance %dcm", distance);

    if(getButtonPress(buttonUp) == 1)
    {
      distance++;
      sleep(250);
    }

    if(getButtonPress(buttonDown) == 1)
    {
      distance--;
      sleep(250);
    }

    if(getButtonPress(buttonRight) == 1)
    {
      setDistance = distance
      sleep(250);
      break;
    }

    sleep(250);
  }

  eraseDisplay();
  displayBigTextLine(3, "Waking up Robot ...");
  sleep(3000);
  displayBigTextLine(3, ".......");
  sleep(3000);
  setSoundVolume(30);
  drawBmpfile(0, 127, "Tired left");
  playSoundFile("Okay");
  sleep(3000);
  eraseDisplay();
  displayBigTextLine(3, "Travel Distance Set");
  displayBigTextLine(6, "	%dcm", setDistance);
  sleep(3000);
  setLEDColor(ledRed);
  sleep(1500);
  setLEDColor(ledOrange);
  clearSounds();
  sleep(1500);
  setLEDColor(ledGreen);
  clearSounds();
  sleep(1500);
  playSoundFile("Horn 1");
  sleep(1500);



	int wheelDiameter = 7;

	float circumference = 3.14 * wheelDiameter;

	float numberOfRotations = Distance / circumference;

	forward(numberOfRotations, rotations, 30);

	sleep(3000);

	backward(numberOfRotations, rotations, 30);

}
