#pragma config(Sensor, S2,     ultrasonic,     sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     gyro,           sensorEV3_Gyro)
#pragma config(Sensor, S4,     colour,         sensorEV3_Color)
#pragma config(Motor,  motorA,          mediumMotor,   tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorD,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//




task main()
{

		int Distance = 105;
		int wheelDiameter = 7;

		float circumference = 3.14 * wheelDiameter;

		float numberOfRotations = Distance / circumference;

		forward(numberOfRotations, rotations, 30);

		sleep(3000);

		backward(numberOfRotations, rotations, 30);

}
